# Generated by Django 3.2.3 on 2021-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='XXX', max_length=255),
            preserve_default=False,
        ),
    ]
