# Generated by Django 3.2.3 on 2021-05-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth1.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='spravka',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
